import 'demo_catalog.dart';

/// Bakery demo catalog.
const bakeryCatalog = DemoCatalog(
  categories: ['Breads', 'Cakes', 'Pastries', 'Cookies', 'Beverages'],
  products: [
    DemoProduct(
      name: 'Whole Wheat Bread',
      code: 'BKY-BRD-001',
      category: 'Breads',
      purchasePrice: 28,
      sellingPrice: 45,
      mrp: 50,
      taxPercent: 5,
      unit: 'loaf',
      stock: 40,
      lowStock: 8,
    ),
    DemoProduct(
      name: 'Butter Croissant',
      code: 'BKY-CRS-001',
      category: 'Pastries',
      purchasePrice: 22,
      sellingPrice: 40,
      mrp: 45,
      taxPercent: 5,
      unit: 'piece',
      stock: 60,
      lowStock: 12,
    ),
    DemoProduct(
      name: 'Chocolate Cake 1kg',
      code: 'BKY-CAK-001',
      category: 'Cakes',
      purchasePrice: 320,
      sellingPrice: 550,
      mrp: 600,
      taxPercent: 18,
      unit: 'piece',
      stock: 15,
      lowStock: 4,
    ),
    DemoProduct(
      name: 'Blueberry Muffin',
      code: 'BKY-MUF-001',
      category: 'Pastries',
      purchasePrice: 25,
      sellingPrice: 50,
      mrp: 55,
      taxPercent: 5,
      unit: 'piece',
      stock: 50,
      lowStock: 10,
    ),
    DemoProduct(
      name: 'Choco Chip Cookies 250g',
      code: 'BKY-COK-001',
      category: 'Cookies',
      purchasePrice: 40,
      sellingPrice: 75,
      mrp: 80,
      taxPercent: 12,
      unit: 'pack',
      stock: 70,
      lowStock: 15,
    ),
    DemoProduct(
      name: 'Red Velvet Pastry',
      code: 'BKY-PST-001',
      category: 'Pastries',
      purchasePrice: 35,
      sellingPrice: 65,
      mrp: 70,
      taxPercent: 18,
      unit: 'piece',
      stock: 30,
      lowStock: 6,
    ),
    DemoProduct(
      name: 'Garlic Breadstick',
      code: 'BKY-BRD-002',
      category: 'Breads',
      purchasePrice: 18,
      sellingPrice: 35,
      mrp: 40,
      taxPercent: 5,
      unit: 'pack',
      stock: 45,
      lowStock: 10,
    ),
    DemoProduct(
      name: 'Cappuccino',
      code: 'BKY-BEV-001',
      category: 'Beverages',
      purchasePrice: 20,
      sellingPrice: 60,
      mrp: 60,
      taxPercent: 5,
      unit: 'cup',
      stock: 100,
      lowStock: 20,
    ),
  ],
);
