import 'demo_catalog.dart';

/// Electronics store demo catalog.
const electronicsCatalog = DemoCatalog(
  categories: ['Televisions', 'Audio', 'Mobiles', 'Computers', 'Accessories'],
  products: [
    DemoProduct(
      name: 'Smart TV 55"',
      code: 'EL-TV-001',
      category: 'Televisions',
      purchasePrice: 38000,
      sellingPrice: 45000,
      mrp: 49999,
      taxPercent: 18,
      unit: 'piece',
      stock: 10,
      lowStock: 3,
    ),
    DemoProduct(
      name: 'Wireless Headphones',
      code: 'EL-AUD-001',
      category: 'Audio',
      purchasePrice: 1600,
      sellingPrice: 2500,
      mrp: 2999,
      taxPercent: 18,
      unit: 'piece',
      stock: 25,
      lowStock: 5,
    ),
    DemoProduct(
      name: 'Bluetooth Speaker',
      code: 'EL-AUD-002',
      category: 'Audio',
      purchasePrice: 1200,
      sellingPrice: 1999,
      mrp: 2299,
      taxPercent: 18,
      unit: 'piece',
      stock: 30,
      lowStock: 6,
    ),
    DemoProduct(
      name: 'Smartphone X 128GB',
      code: 'EL-MOB-001',
      category: 'Mobiles',
      purchasePrice: 14500,
      sellingPrice: 17999,
      mrp: 19999,
      taxPercent: 18,
      unit: 'piece',
      stock: 18,
      lowStock: 4,
    ),
    DemoProduct(
      name: 'Laptop 14" i5',
      code: 'EL-COM-001',
      category: 'Computers',
      purchasePrice: 42000,
      sellingPrice: 52000,
      mrp: 56999,
      taxPercent: 18,
      unit: 'piece',
      stock: 8,
      lowStock: 2,
    ),
    DemoProduct(
      name: 'Wireless Mouse',
      code: 'EL-ACC-001',
      category: 'Accessories',
      purchasePrice: 350,
      sellingPrice: 699,
      mrp: 799,
      taxPercent: 18,
      unit: 'piece',
      stock: 60,
      lowStock: 12,
    ),
    DemoProduct(
      name: 'USB-C Cable 1m',
      code: 'EL-ACC-002',
      category: 'Accessories',
      purchasePrice: 90,
      sellingPrice: 249,
      mrp: 299,
      taxPercent: 18,
      unit: 'piece',
      stock: 120,
      lowStock: 20,
    ),
    DemoProduct(
      name: 'Power Bank 10000mAh',
      code: 'EL-ACC-003',
      category: 'Accessories',
      purchasePrice: 700,
      sellingPrice: 1199,
      mrp: 1399,
      taxPercent: 18,
      unit: 'piece',
      stock: 40,
      lowStock: 8,
    ),
  ],
);
