import 'demo_catalog.dart';

/// Garment / apparel store demo catalog.
const garmentCatalog = DemoCatalog(
  categories: ['Men', 'Women', 'Kids', 'Footwear', 'Accessories'],
  products: [
    DemoProduct(
      name: "Men's Cotton T-Shirt",
      code: 'GRM-MEN-001',
      category: 'Men',
      purchasePrice: 180,
      sellingPrice: 399,
      mrp: 499,
      taxPercent: 5,
      unit: 'piece',
      stock: 50,
      lowStock: 10,
    ),
    DemoProduct(
      name: 'Formal Shirt',
      code: 'GRM-MEN-002',
      category: 'Men',
      purchasePrice: 420,
      sellingPrice: 899,
      mrp: 1099,
      taxPercent: 12,
      unit: 'piece',
      stock: 30,
      lowStock: 6,
    ),
    DemoProduct(
      name: "Women's Kurti",
      code: 'GRM-WMN-001',
      category: 'Women',
      purchasePrice: 350,
      sellingPrice: 799,
      mrp: 999,
      taxPercent: 12,
      unit: 'piece',
      stock: 40,
      lowStock: 8,
    ),
    DemoProduct(
      name: 'Cotton Saree',
      code: 'GRM-WMN-002',
      category: 'Women',
      purchasePrice: 650,
      sellingPrice: 1499,
      mrp: 1799,
      taxPercent: 12,
      unit: 'piece',
      stock: 25,
      lowStock: 5,
    ),
    DemoProduct(
      name: 'Kids Denim Jeans',
      code: 'GRM-KID-001',
      category: 'Kids',
      purchasePrice: 250,
      sellingPrice: 599,
      mrp: 699,
      taxPercent: 5,
      unit: 'piece',
      stock: 35,
      lowStock: 7,
    ),
    DemoProduct(
      name: 'Sports Shoes',
      code: 'GRM-FTW-001',
      category: 'Footwear',
      purchasePrice: 900,
      sellingPrice: 1999,
      mrp: 2499,
      taxPercent: 18,
      unit: 'pair',
      stock: 20,
      lowStock: 4,
    ),
    DemoProduct(
      name: 'Leather Belt',
      code: 'GRM-ACC-001',
      category: 'Accessories',
      purchasePrice: 150,
      sellingPrice: 399,
      mrp: 499,
      taxPercent: 12,
      unit: 'piece',
      stock: 45,
      lowStock: 9,
    ),
    DemoProduct(
      name: 'Woolen Cap',
      code: 'GRM-ACC-002',
      category: 'Accessories',
      purchasePrice: 80,
      sellingPrice: 199,
      mrp: 249,
      taxPercent: 5,
      unit: 'piece',
      stock: 55,
      lowStock: 10,
    ),
  ],
);
