import 'demo_catalog.dart';

/// Kirana / grocery demo catalog (the original Pocket POS sample data).
const groceryCatalog = DemoCatalog(
  categories: ['Groceries', 'Beverages', 'Dairy', 'Snacks', 'Personal Care'],
  products: [
    DemoProduct(
      name: 'Premium Rice 5kg',
      code: 'PRD-RICE-001',
      barcode: '8900000000011',
      category: 'Groceries',
      purchasePrice: 410,
      sellingPrice: 460,
      mrp: 480,
      taxPercent: 5,
      unit: 'bag',
      stock: 35,
      lowStock: 8,
    ),
    DemoProduct(
      name: 'Sunflower Oil 1L',
      code: 'PRD-OIL-001',
      barcode: '8900000000028',
      category: 'Groceries',
      purchasePrice: 128,
      sellingPrice: 145,
      mrp: 150,
      taxPercent: 5,
      unit: 'bottle',
      stock: 22,
      lowStock: 6,
    ),
    DemoProduct(
      name: 'Cola 750ml',
      code: 'PRD-COLA-001',
      barcode: '8900000000035',
      category: 'Beverages',
      purchasePrice: 32,
      sellingPrice: 40,
      mrp: 42,
      taxPercent: 12,
      unit: 'bottle',
      stock: 48,
      lowStock: 10,
    ),
    DemoProduct(
      name: 'Toned Milk 1L',
      code: 'PRD-MLK-001',
      barcode: '8900000000042',
      category: 'Dairy',
      purchasePrice: 49,
      sellingPrice: 54,
      mrp: 56,
      taxPercent: 5,
      unit: 'packet',
      stock: 60,
      lowStock: 12,
    ),
    DemoProduct(
      name: 'Butter Biscuit 200g',
      code: 'PRD-BISC-001',
      barcode: '8900000000059',
      category: 'Snacks',
      purchasePrice: 18,
      sellingPrice: 24,
      mrp: 25,
      taxPercent: 12,
      unit: 'pack',
      stock: 85,
      lowStock: 15,
    ),
    DemoProduct(
      name: 'Whole Wheat Atta 10kg',
      code: 'PRD-ATTA-001',
      barcode: '8900000000066',
      category: 'Groceries',
      purchasePrice: 360,
      sellingPrice: 420,
      mrp: 430,
      taxPercent: 5,
      unit: 'bag',
      stock: 26,
      lowStock: 6,
    ),
    DemoProduct(
      name: 'Bath Soap 125g',
      code: 'PRD-SOAP-001',
      barcode: '8900000000073',
      category: 'Personal Care',
      purchasePrice: 28,
      sellingPrice: 35,
      mrp: 36,
      taxPercent: 18,
      unit: 'piece',
      stock: 110,
      lowStock: 20,
    ),
  ],
);
