import 'demo_catalog.dart';

/// Pharmacy / medical store demo catalog.
const pharmacyCatalog = DemoCatalog(
  categories: ['Pain Relief', 'Cold & Flu', 'Vitamins', 'First Aid', 'Personal Care'],
  products: [
    DemoProduct(
      name: 'Paracetamol 500mg (10 tab)',
      code: 'PHM-PAI-001',
      category: 'Pain Relief',
      purchasePrice: 12,
      sellingPrice: 20,
      mrp: 22,
      taxPercent: 12,
      unit: 'strip',
      stock: 120,
      lowStock: 25,
    ),
    DemoProduct(
      name: 'Ibuprofen 400mg (10 tab)',
      code: 'PHM-PAI-002',
      category: 'Pain Relief',
      purchasePrice: 18,
      sellingPrice: 30,
      mrp: 34,
      taxPercent: 12,
      unit: 'strip',
      stock: 80,
      lowStock: 20,
    ),
    DemoProduct(
      name: 'Cough Syrup 100ml',
      code: 'PHM-CLD-001',
      category: 'Cold & Flu',
      purchasePrice: 55,
      sellingPrice: 89,
      mrp: 95,
      taxPercent: 12,
      unit: 'bottle',
      stock: 40,
      lowStock: 10,
    ),
    DemoProduct(
      name: 'Vitamin C Tablets (30)',
      code: 'PHM-VIT-001',
      category: 'Vitamins',
      purchasePrice: 90,
      sellingPrice: 149,
      mrp: 165,
      taxPercent: 12,
      unit: 'bottle',
      stock: 50,
      lowStock: 10,
    ),
    DemoProduct(
      name: 'Multivitamin (60)',
      code: 'PHM-VIT-002',
      category: 'Vitamins',
      purchasePrice: 210,
      sellingPrice: 349,
      mrp: 399,
      taxPercent: 12,
      unit: 'bottle',
      stock: 30,
      lowStock: 6,
    ),
    DemoProduct(
      name: 'Antiseptic Cream 30g',
      code: 'PHM-FST-001',
      category: 'First Aid',
      purchasePrice: 40,
      sellingPrice: 72,
      mrp: 80,
      taxPercent: 12,
      unit: 'tube',
      stock: 60,
      lowStock: 12,
    ),
    DemoProduct(
      name: 'Adhesive Bandage (pack)',
      code: 'PHM-FST-002',
      category: 'First Aid',
      purchasePrice: 25,
      sellingPrice: 49,
      mrp: 55,
      taxPercent: 12,
      unit: 'pack',
      stock: 70,
      lowStock: 15,
    ),
    DemoProduct(
      name: 'Hand Sanitizer 500ml',
      code: 'PHM-PER-001',
      category: 'Personal Care',
      purchasePrice: 85,
      sellingPrice: 149,
      mrp: 160,
      taxPercent: 18,
      unit: 'bottle',
      stock: 45,
      lowStock: 10,
    ),
  ],
);
