// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTDQy7I8UiNsOe4hDmlnp11ou5T5rVwNg',
    appId: '1:1086638616306:web:0fbdebd0577551649dea6b',
    messagingSenderId: '1086638616306',
    projectId: 'mypocketpos',
    authDomain: 'mypocketpos.firebaseapp.com',
    storageBucket: 'mypocketpos.firebasestorage.app',
    measurementId: 'G-J0YSZ6G07C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe02E-0kQbI4PMxxES4dYyD5RlqyuiOsw',
    appId: '1:1086638616306:android:f237e242a2999b849dea6b',
    messagingSenderId: '1086638616306',
    projectId: 'mypocketpos',
    storageBucket: 'mypocketpos.firebasestorage.app',
  );
}
