// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOBS028sisdT1o8QUf2F5abIfIzAHmZ68',
    appId: '1:351899337586:web:5d7e28df8d0276e92653eb',
    messagingSenderId: '351899337586',
    projectId: 'pocket-pos-35e48',
    authDomain: 'pocket-pos-35e48.firebaseapp.com',
    storageBucket: 'pocket-pos-35e48.firebasestorage.app',
    measurementId: 'G-0NTBQFMX1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACG6cYC3LtyefLjcGqYAo3rAZgb9ldxFs',
    appId: '1:351899337586:android:b66d7bf054f6a45a2653eb',
    messagingSenderId: '351899337586',
    projectId: 'pocket-pos-35e48',
    storageBucket: 'pocket-pos-35e48.firebasestorage.app',
  );
}
